### PR TITLE
Fix tactical screen scroll freeze

### LINKED ISSUE #1122: Unable to scroll screen when entering turn mode
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1 and master | JA2 1.03 Steam|   no    |    not sure     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)

When your merc sees an enemy when the mouse is held down, the scroll will not work. It will get back to normal if you do some keyboard shortcut, or switch to strategic map view and switch back.

To reproduce, start a fresh new game:
- After arrival in A9, shoot the gun so enemies will start coming
- Hold the left mouse button down (e.g. drag a selection box and hold)
- When enemy comes, the game switches to turn-based mode
- Release the mouse now. The screen is no longer scrollable. Radar map not working.
- Some actions that can unlock the scroll:
  - Moving the merc,
  - Selecting another merc by clicking in tactical screen (not the bottom menu),
  - Switching to strategic map screen and switch back,
  - Auto bandaging by hotkey, or
  - Quick save and load (Alt+S, Alt+L)

Maybe the mouse state is messed up.

See an example here: https://youtu.be/Pr0I1_EOD5Y?t=819

Cannot reproduce in vanilla (Steam version 1.03).

OS is Win 10.

[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

### PR DESCRIPTION
**Pull request by ja2-derek**
Analysis here: https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1122#issuecomment-650511871

Fixes #1122. Preserves the behavior of #565.

This fix ensures scrolling is un-freezed when we enter combat mode during rubber-banding. Also re-tested #550.

### CODE REVIEW

File: src/game/Tactical/Interface_Control.cc [hunk 1]
```diff
@@ -596,8 +596,6 @@ void ResetInterfaceAndUI( )
 
 	EraseRenderArrows( );
 
-	EndRubberBanding( );
```
Comment (ja2-derek) [inline src/game/Tactical/Interface_Control.cc:599]: This is already called in EraseInterfaceMenus()

**Comment by lynxlynxlynx** [comment]
Nice!
