### PR TITLE
Fix vfs priority issues

### LINKED ISSUE #2159: Broken JSON file load order
Seems like vanilla mercs-profiles.json wins over that of return-to-san-amaro on the latest build despite having lower priority:
```
[INFO] stracciatella::vfs: VFS item with priority 26: DirFs { "C:\\Repos\\ja2-stracciatella\\_bin\\Debug\\mods\\imp-quiz-honest-answers\\data" }
[INFO] stracciatella::vfs: VFS item with priority 25: DirFs { "C:\\Repos\\ja2-stracciatella\\_bin\\Debug\\mods\\return-to-san-amaro\\data" }
[INFO] stracciatella::vfs: VFS item with priority 24: DirFs { "C:\\Repos\\ja2-stracciatella\\_bin\\Debug\\externalized" }
[INFO] stracciatella::vfs: VFS item with priority 23: DirFs { "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Jagged Alliance 2 Gold\\data" }
```
Steps to reproduce:
1. Make these changes:
Mod's mercs-profiles.json:
 ` { "profileID": 0,  "internalName": "BARRY", "nickname": "MODDED", "type": "AIM" }`
Vanilla's mercs-profiles.json:
` { "profileID": 0,  "internalName": "BARRY", "nickname": "VANILLA", "type": "AIM" }`
2. Launch the game, open the mugshot index. His name will be displayed as VANILLA

Unfortunately, I can't fix it myself in a timely manner because I failed making embedded Rust work on my VS setup with functioning debugger and all.

### PR DESCRIPTION
**Pull request by selaux**
- Invert priority for loaded mods as discussed in https://github.com/ja2-stracciatella/ja2-stracciatella/pull/2109
- Reflect priority change in the loader and add hint
- Fix priority in `read_patched_json`. Fixes #2159 
- Prioritize home dir above mods: So home dir can e.g. include compatibility fixes between mods
- Use BTreeSet for listing directories, so the order is deterministic (e.g. when adding SLF layers)
- Log layer where file is found when opening files

image

### CODE REVIEW

File: src/launcher/StracciatellaLauncher.cc [hunk 1]
```diff
@@ -61,39 +61,42 @@ StracciatellaLauncher::StracciatellaLauncher() {
...
-          { disableModsButton = new Fl_Button(245, 115, 30, 30, "@>");
+          { disableModsButton = new Fl_Button(245, 135, 30, 30, "@>");
             disableModsButton->tooltip("Disable one or multiple mods.");
             disableModsButton->deactivate();
           } // Fl_Button* disableModsButton
-          { moveUpModsButton = new Fl_Button(245, 155, 30, 30, "@2<");
-            moveUpModsButton->tooltip("Increase mod priority. If a resource file is present in multiple mods, the fi\
-le from the mod with the highest priority is used.");
+          { moveUpModsButton = new Fl_Button(245, 175, 30, 30, "@2<");
+            moveUpModsButton->tooltip("Move mod up in the list and decrease mod priority..");
```
Comment (lynxlynxlynx) [inline src/launcher/StracciatellaLauncher.cc:78]: Here and in the next  chunk it should either be one full stop or three (or the Unicode ellipsis if anyone wants to be pedantic).

**Comment by lynxlynxlynx** [comment]
Other than that, LGTM! I guess the logging change is not too spammy considering we had something in DefaultContentManager before already?

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by selaux** [comment]
> Other than that, LGTM! I guess the logging change is not too spammy considering we had something in DefaultContentManager before already?

It's as spammy as the previous version, but a bit more spammy than the previous master, as the `open_in_layer` method didn't log anything.
