### PR TITLE
Fix time consuming logging

### LINKED ISSUE #1136: Game gets choppy in tactical real-time mode
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master | Steam version |    no    |    not sure     |

I notice the game gets choppy, and scrolls and UI responses are noticably delayed in certain situations. The delay starts in the middle of a fight, and when multiple enemies are on high alert. But it does not always happen.

I am running master build on Win 10. I am not sure if this issue is specific to me, as I haven't seen any other reports about performance. I remember seeing this is also in 0.16.1 in late game sectors, but I am not able to reproduce this issue from scratch - e.g. starting fresh game, teleporting to P3 does not reproduce it.

I did a profiling during the stuttering, and the results points to excessive debug logging. Game was not in debug mode during profiling.

Function breakdown by CPU time used:
Perf01

Call stack of LogMessage:
PERF02

As seen above, the problem is the debug logging the `RadioSighting` method. It takes about a third of the total CPU time spent. The choppiness seems to be gone when I commented out all those debug logs.

While I am not 100% certain about the root cause (as it is not easily reproducible), there should be no harm reducing debug logs. I suggest that we:

- [ ] Reduce or remove debug logging in the inner loops of `RadioSighting`
- [ ] ~Update `SLOGD`, to not do anything unless debug log is enabled~
- [ ] Improve efficiency of Logger_log in lib-stracc (#1137)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

### PR DESCRIPTION
**Pull request by selaux**
Fixes #1136 

Should optimize logging performance in general:

- Dont build log record when it is filtered anyways
- Pass filename via Macro to Rust instead of building it from the full path in rust

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Nice and fast. :)

File: src/sgp/Logger.h [hunk 1]
```diff
@@ -8,19 +8,22 @@
 void LogMessage(bool isAssert, LogLevel level, const char* file, const ST::string& str);
 void LogMessage(bool isAssert, LogLevel level, const char *file, const char *format, ...);
 
+/** Get filename relative to src directory */
+#define __FILENAME__ (__FILE__ + SOURCE_PATH_SIZE)
```
Comment (lynxlynxlynx) [inline src/sgp/Logger.h:12]: Mac worker really doesn't like this, so the build logs are full of warnings (sextupling their size):
```
2020-07-12T10:38:01.4168070Z /Users/runner/work/ja2-stracciatella/ja2-stracciatella/src/game/SaveLoadGame.cc:1304:3: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
2020-07-12T10:38:01.4169070Z                 Assert(s->ubID == i);
2020-07-12T10:38:01.4169370Z                 ^~~~~~~~~~~~~~~~~~~~
2020-07-12T10:38:01.4170570Z /Users/runner/work/ja2-stracciatella/ja2-stracciatella/src/sgp/Debug.h:10:41: note: expanded from macro 'Assert'
2020-07-12T10:38:01.4170880Z #define Assert(a)       (a) ? (void)0 : SLOGA("Assertion failed in %s, line %d", __FILE__, __LINE__)
2020-07-12T10:38:01.4171160Z                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-07-12T10:38:01.4172240Z /Users/runner/work/ja2-stracciatella/ja2-stracciatella/src/sgp/Logger.h:27:62: note: expanded from macro 'SLOGA'
2020-07-12T10:38:01.4172580Z #define SLOGA(FORMAT, ...) LogMessage(true, LogLevel::Error, __FILENAME__, FORMAT, ##__VA_ARGS__)
2020-07-12T10:38:01.4172870Z                                                              ^~~~~~~~~~~~
2020-07-12T10:38:01.4173830Z /Users/runner/work/ja2-stracciatella/ja2-stracciatella/src/sgp/Logger.h:12:32: note: expanded from macro '__FILENAME__'
2020-07-12T10:38:01.4174140Z #define __FILENAME__ (__FILE__ + SOURCE_PATH_SIZE)
2020-07-12T10:38:01.4174390Z                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

Comment (ja2-derek) [reply src/sgp/Logger.h:12]: Fixed via #1246
