### PR TITLE
fixed smoke leaving roof edge

### LINKED ISSUE #600: Smoke/Gas spreads over roof edge
I threw a tear gas grenade near the edge of a roof and the gas spred over the edge of the roof.

### PR DESCRIPTION
**Pull request by daviel**
Fixes #600 
Check for existent structure on the spot and the bLevel. If there isn't any structure we can't spread the smoke.

### CODE REVIEW

File: src/game/TileEngine/Explosion_Control.cc [hunk 1]
```diff
@@ -1530,6 +1530,17 @@ static void GetRayStopInfo(UINT32 uiNewSpot, UINT8 ubDir, INT8 bLevel, BOOLEAN f
...
+  if (bLevel == 1)
+  {
+    // We check for roof-level and structure to prevent smoke spreading over roof
+    STRUCTURE * pStructure = FindStructure( uiNewSpot, STRUCTURE_ROOF );
+    if (pStructure == NULL)
+    {
+      // no structure found therefore we can't spread
+      ( *pubKeepGoing ) = FALSE;	   
+    }
+  }
```
Comment (lynxlynxlynx) [inline src/game/TileEngine/Explosion_Control.cc]: at minimum this needs indentation with tabs, not spaces.

**Comment by daviel** [comment]
Intendation should be fixed now.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by Manuel-K** [comment]
Oops. We don't need this twice in the milestone.
