### PR TITLE
Extract easing from DoTransitionFromPreBattleInterfaceToAutoResolve

### LINKED ISSUE #381: autoresolve crash
Found while trying to reproduce something else, so it's mostly a dump

Steps to reproduce: have a sector attacked by the enemy and autoresolve it. You probably need at least one merc in it already.

> #0  0x000000000082680a in BltStretchVideoSurface (dst=0x1211550, src=0x146aa10, src_rect=0x190f04c, dst_rect=0x7fffffffb8e0) at sgp/VSurface.cc:400
> #1  0x00000000005bd3a6 in DoTransitionFromPreBattleInterfaceToAutoResolve () at Build/Strategic/Auto_Resolve.cc:447
> #2  0x00000000005bd65a in AutoResolveScreenHandle () at Build/Strategic/Auto_Resolve.cc:539
> #3  0x00000000007d4f02 in GameLoop () at Build/GameLoop.cc:298

Thats a corruption at:

> 400                                     *d++ = *s;
> (gdb) p d
> $1 = (UINT16 *) 0x8001f170f794
> (gdb) p s
> $2 = (const UINT16 *) 0x149f982

From a cursory glance the only interesting thing is that the dest surface dimensions are quite big, higher than the resolution used.

> (gdb) p dst_rect->w
> $12 = 2397
> (gdb) p dst_rect->h
> $13 = 1310

### PR DESCRIPTION
**Pull request by selaux**
Fixes #381 

- Replace custom easing function with standard cubic one
- Reduce complexity of function

### CODE REVIEW

File: Build/Strategic/Auto_Resolve.cc [hunk 1]
```diff
@@ -419,37 +409,24 @@ static void DoTransitionFromPreBattleInterfaceToAutoResolve(void)
...
-		uFactor = (uPercentage - 50) * 2;
-		if( uPercentage < 50 )
-			uPercentage = (UINT16)(uPercentage + uPercentage * uFactor * 0.01 + 0.5);
-		else
-			uPercentage = (UINT16)(uPercentage + (100-uPercentage) * uFactor * 0.01 + 0.05);
-
-		//Calculate the center point.
-		UINT16 const uLeft = uStartLeft + (uEndLeft - uStartLeft + 1) * uPercentage / 100;
-		UINT16 const uTop  = uStartTop  + (uEndTop  - uStartTop  + 1) * uPercentage / 100;
+    FLOAT fEasingProgress = EaseInCubic(uiStartTime, uiEndTime, GetClock());
```
Comment (lynxlynxlynx) [inline Build/Strategic/Auto_Resolve.cc]: whitespace, the bane of reviews.

Comment (selaux) [inline Build/Strategic/Auto_Resolve.cc]: Done.
