### PR TITLE
Fix #671

### LINKED ISSUE #671: Assert on sector entry: militia promotion elsewhere
> 2018/00/06 20:58:03 ERROR   [Asserts         ] Assertion failed in /home/kajak/games/ja2-stracciatella/src/game/Strategic/Town_Militia.cc, line 217
> 
> Thread 1 "ja2" received signal SIGABRT, Aborted.
> __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
> 58      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> (gdb) bt
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
> #1  0x00007ffff681537a in __GI_abort () at abort.c:89
> #2  0x0000555555a83f83 in SLOG_LogMessage (level=SLOG_ERROR, tag=DEBUG_TAG_ASSERTS, 
>     format=0x555555ac1668 "Assertion failed in %s, line %d\n")
>     at /home/kajak/games/ja2-stracciatella/src/slog/slog.c:252
> #3  0x0000555555841b49 in StrategicPromoteMilitiaInSector (x=15, y=4, current_rank=0 '\000', n=1 '\001')
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/Town_Militia.cc:217
> #4  0x0000555555841d11 in CheckOneMilitiaForPromotion (x=15, y=4, current_rank=0 '\000', 
>     kill_points=3 '\003') at /home/kajak/games/ja2-stracciatella/src/game/Strategic/Town_Militia.cc:258
> #5  0x00005555558d1cd6 in HandleMilitiaPromotions ()
>     at /home/kajak/games/ja2-stracciatella/src/game/Tactical/Militia_Control.cc:75
> #6  0x000055555584290b in HandleMilitiaStatusInCurrentMapBeforeLoadingNewMap ()
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/Town_Militia.cc:609
> #7  0x00005555558208cd in HandleDefiniteUnloadingOfWorld (ubUnloadCode=0 '\000')
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/StrategicMap.cc:3421
> #8  0x000055555581b1db in SetCurrentWorldSector (x=12, y=6, z=0 '\000')
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/StrategicMap.cc:574
> #9  0x00005555557f32ee in HandleExitsFromMapScreen ()
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/Map_Screen_Interface_Bottom.cc:1204
> #10 0x00005555557da023 in MapScreenHandle ()
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/MapScreen.cc:2093
> ---Type <return> to continue, or q <return> to quit---
> #11 0x00005555559e056d in GameLoop () at /home/kajak/games/ja2-stracciatella/src/game/GameLoop.cc:200

> (gdb) f 3
> #3  0x0000555555841b49 in StrategicPromoteMilitiaInSector (x=15, y=4, current_rank=0 '\000', n=1 '\001')
>     at /home/kajak/games/ja2-stracciatella/src/game/Strategic/Town_Militia.cc:217
> 217             Assert(si.ubNumberOfCivsAtLevel[current_rank] >= n);

Dumping this here while I investigate. Fought a militia battle with them and apparently some should habe gotten promoted. However I didn't reenter the sector, so now it exploded when entering another with a random npc (0 >= 1). 

Another potential source of problems is that by this time all training finished, so all militia was restocked and became light blue, while this is trying to promote greenhorns.

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
counts the kills towards the actual next rank

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Manually cancelled two of them.

File: src/game/Strategic/Town_Militia.cc [hunk 1]
```diff
@@ -246,8 +246,16 @@ void StrategicRemoveMilitiaFromSector(INT16 sMapX, INT16 sMapY, UINT8 ubRank, UI
 
 
 // kill pts are (2 * kills) + assists
-UINT8 CheckOneMilitiaForPromotion(INT16 const x, INT16 const y, UINT8 const current_rank, UINT8 kill_points)
+UINT8 CheckOneMilitiaForPromotion(INT16 const x, INT16 const y, UINT8 &current_rank, UINT8 kill_points)
 {
+	// since the awarding is potentially significantly delayed, make sure they
+	// weren't all promoted already by regular training or killed
+	SECTORINFO& si = SectorInfo[SECTOR(x, y)];
+	while (si.ubNumberOfCivsAtLevel[current_rank] == 0) {
```
Comment (Manuel-K) [inline src/game/Strategic/Town_Militia.cc]: Because this is passed by reference, I think this should have an additional comment. Something like determine minimal applicable rank.

Comment (lynxlynxlynx) [reply src/game/Strategic/Town_Militia.cc]: is it not clear from the code?

Comment (Manuel-K) [reply src/game/Strategic/Town_Militia.cc]: I hate it when references are changed without comments. Preferably at the top of the function.

Comment (lynxlynxlynx) [reply src/game/Strategic/Town_Militia.cc]: Both are already true ... but I'll go add an extra line.

**Comment by lynxlynxlynx** [comment]
So, any objections to merging?

**Comment by Manuel-K** [comment]
No. 

Caveat: This opinion is only based on a review of the code – not a test.
