### PR TITLE
Fix out of bounds access in DecideActionRed.

### LINKED ISSUE #378: Out of bounds access in DecideAction.cc:1757:41
It can happen that BestThrow.bWeaponIn == NO_SLOT and NO_SLOT == -1.
I'm not sure, it may be that BestThrow.bWeaponIn is always -1 in this place.

### PR DESCRIPTION
**Pull request by flaviojs**
BestThrow.bWeaponIn can be NO_SLOT (-1) which leads to a silent out of
bounds access and an usItem value that I can't predict.

Closes #378

### CODE REVIEW

File: src/game/TacticalAI/DecideAction.cc [hunk 1]
```diff
@@ -1749,7 +1749,7 @@ INT8 DecideActionRed(SOLDIERTYPE *pSoldier, UINT8 ubUnconsciousOK)
 
 			return(AI_ACTION_TOSS_PROJECTILE);
 		}
-		else		// toss/throw/launch not possible
+		else if (BestThrow.bWeaponIn != NO_SLOT)		// toss/throw/launch not possible
```
Comment (lynxlynxlynx) [inline src/game/TacticalAI/DecideAction.cc]: 1. What about the case of !BestThrow.ubPossible && BestThrow.bWeaponIn == NO_SLOT? It's not handled now, but went into this block before.
2. The comment is now confusing, since taken alone it looks wrong.

Comment (flaviojs) [reply src/game/TacticalAI/DecideAction.cc]: It will continue to the code after the block, like it should (no item = no range).
I'll move the check to the inner `if`, that should take care of the confusing comment(s).

Comment (lynxlynxlynx) [reply src/game/TacticalAI/DecideAction.cc]: Yeah, much better, thanks.
