### PR TITLE
Externalizing Creature Lairs and Spreading

### LINKED ISSUE #1087: "Travel to Surface?" prompt do not work in Cambria/Alma mine
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master/nightly/0.16.1 |  JA2 Steam version |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

There should be a "Travel to surface?" prompt, when the squad exits the deep underground lair sectors after clearing out the lair. This prompt works if lair is in Drassen, but it does not prompt if it is Cambria (Alma should have same problem but I have not tested)

I found the issue when I was looking into externalizing creature lair data. This is an old bug, might be a vanilla bug as well.

The issue is a mismatch of lair ID:

Cambria lair ID is `2`
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/9f76684de4cbab33ad8e31d756d2e6f5de44ede5/src/game/Strategic/Creature_Spreading.cc#L174-L177

The wrap code function has the wrong ID:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/9f76684de4cbab33ad8e31d756d2e6f5de44ede5/src/game/Strategic/Creature_Spreading.cc#L1366

So the warp code never matches in Cambria or Alma. 

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

### PR DESCRIPTION
**Pull request by ja2-derek**
Fixes #1087.

See also #1095 and #665.

## Summary

- Extracted JSON data from Creature_Spreading.cc (`strategic-map-creature-lairs.json`)
- Removed `isInfestible` from Mine. It is redundant. The existence of a CreatureLairModel means the same.

### Model fields data

_All data come from Creature_Spreading.cc_

- InitLair`${TOWN}` => `"sectors"`
- InitCreatureQuest: `curr->uiFlags |= SF_PENDING_ALTERNATE_MAP;` => `"entranceSector"`
- ChooseTownSectorToAttack => `"attackSectors"`
- MineClearOfMonsters => MineModel::`mineSectors` (#1098)
- GetWarpOutOfMineCodes => `"warpExit"`

## Does not cover

 - Hard-coded Tixa dungeon references (in StrategicMap.cc, etc)

### CODE REVIEW

File: src/externalized/strategic/CreatureLairModel.cc [hunk 1]
```diff
@@ -0,0 +1,259 @@
...
+	if (code == "NORTH") return INSERTION_CODE_NORTH;
+	if (code == "SOUTH") return INSERTION_CODE_SOUTH;
+	if (code == "EAST") return INSERTION_CODE_EAST;
+	if (code == "WEST") return INSERTION_CODE_WEST;
+	if (code == "GRIDNO") return INSERTION_CODE_GRIDNO;
+	if (code == "ARRIVING_GAME") return INSERTION_CODE_ARRIVING_GAME;
+	if (code == "CHOPPER") return INSERTION_CODE_CHOPPER;
+	if (code == "PRIMARY_EDGEINDEX") return INSERTION_CODE_PRIMARY_EDGEINDEX;
+	if (code == "SECONDARY_EDGEINDEX") return INSERTION_CODE_SECONDARY_EDGEINDEX;
+	if (code == "CENTER") return INSERTION_CODE_CENTER;
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:40]: Might look nicer if it was all stored in a static std::map, though I can't decide if I care enough. :thinking:

File: src/externalized/strategic/CreatureLairModel.cc [hunk 2]
```diff
@@ -0,0 +1,259 @@
...
+		if (lair->associatedMineId > numMines)
+		{
+			SLOGE(ST::format("Invalid mineId {}", lair->associatedMineId));
+			throw std::runtime_error("");
+		}
+		
+		// The first lair sector in list should be QUEEN_LAIR
+		if (lair->lairSectors.size() < 1 || lair->lairSectors[0].habitatType != QUEEN_LAIR)
+		{
+			SLOGW(ST::format("The list of lair sectors should be non-empty and begins with the QUEEN_LAIR. Lair ID: {}", lair->lairId));
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:214]:
```suggestion
			SLOGW(ST::format("The list of lair sectors should be non-empty and begin with the QUEEN_LAIR. Lair ID: {}", lair->lairId));
```

File: src/externalized/strategic/CreatureLairModel.cc [hunk 3]
```diff
@@ -0,0 +1,259 @@
...
+				{
+					SLOGW(ST::format("The current lair sector ({},{}) is not adjacent to the previous. This may indicate data issues", sec.sectorId, sec.sectorLevel));
+				}
+			}
+			x = SECTORX(sec.sectorId);
+			y = SECTORY(sec.sectorId);
+			z = sec.sectorLevel;
+		}
+
+		// all underground sectors must also lbe defined with UndergroundSectorModel
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:234]:
```suggestion
		// all underground sectors must also be defined with UndergroundSectorModel
```

File: src/externalized/strategic/CreatureLairModel.cc [hunk 4]
```diff
@@ -0,0 +1,259 @@
...
+			throw std::runtime_error("");
+		}
+		
+		// The first lair sector in list should be QUEEN_LAIR
+		if (lair->lairSectors.size() < 1 || lair->lairSectors[0].habitatType != QUEEN_LAIR)
+		{
+			SLOGW(ST::format("The list of lair sectors should be non-empty and begins with the QUEEN_LAIR. Lair ID: {}", lair->lairId));
+		}
+
+		// all lair sectors should be adjacent and defined as underground sector
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:217]: From the code it looks like it's not enough that they're adjacent, but also consecutive, iow non-branching. Worth noting in the json field description.

File: src/externalized/strategic/CreatureLairModel.cc [hunk 5]
```diff
@@ -0,0 +1,259 @@
...
+			z = sec.sectorLevel;
+		}
+
+		// all underground sectors must also lbe defined with UndergroundSectorModel
+		bool isDefined = false;
+		for (auto sec : lair->lairSectors)
+		{
+			if (sec.sectorLevel == 0)
+			{
+				SLOGW(ST::format("Lair sector ({}) is not in the underground. There may cause problems.", sec.sectorId));
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:240]:
```suggestion
				SLOGW(ST::format("Lair sector ({}) is not in the underground. This may cause problems.", sec.sectorId));
```

File: src/externalized/strategic/CreatureLairModel.cc [hunk 6]
```diff
@@ -0,0 +1,259 @@
...
+			{
+				if (ug->sectorId == sec.sectorId && ug->sectorZ == sec.sectorLevel)
+				{
+					isDefined = true;
+					break;
+				}
+			}
+			if (!isDefined)
+			{
+				SLOGE(ST::format("Underground lair sector ({},{}) is not defined as underground sectors. Make sure the data in consistent with strategic-map-underground-sectors.json.", sec.sectorId, sec.sectorLevel));
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/CreatureLairModel.cc:254]:
```suggestion
				SLOGE(ST::format("Underground lair sector ({},{}) is not defined as an underground sector. Make sure the data is consistent with strategic-map-underground-sectors.json.", sec.sectorId, sec.sectorLevel));
```

File: src/game/Strategic/Creature_Spreading.cc [hunk 7]
```diff
@@ -148,134 +144,59 @@ static CREATURE_DIRECTIVE* NewDirective(UINT8 ubSectorID, UINT8 ubSectorZ, UINT8
...
 }
 
-
-static void InitLairDrassen(void)
+static void InitCreatureLair(const CreatureLairModel* lairModel)
 {
-	CREATURE_DIRECTIVE *curr;
-	giLairID = 1;
-	//initialize the linked list of lairs
-	lair = NewDirective( SEC_F13, 3, QUEEN_LAIR );
```
Comment (lynxlynxlynx) [inline src/game/Strategic/Creature_Spreading.cc:157]: If I see correctly, nothing uses `NewDirective` any more, so it can go.

File: src/externalized/strategic/CreatureLairModel.cc (hunk 1 above)
Comment (ja2-derek) [reply src/externalized/strategic/CreatureLairModel.cc:40]: I am thinking about a small refactor of all these deserialization logic.

Maybe a `DeserializationUtil` module, which contains all these `enum` mappings, and the `SECTOR_FROM_SECTOR_SHORT_STRING` handling.

File: src/game/Strategic/Creature_Spreading.cc (hunk 7 above)
Comment (ja2-derek) [reply src/game/Strategic/Creature_Spreading.cc:157]: It is still used in ``InitCreatureLair`

File: src/externalized/strategic/CreatureLairModel.cc (hunk 4 above)
Comment (ja2-derek) [reply src/externalized/strategic/CreatureLairModel.cc:217]: Actually that is a "should" and log WARN. It might work to have it non-adjacent or branching. But it probably won't make sense in terms of gameplay and story, that effectively the creatures teleports across the map.

I haven't tested if that introduce other problems. 

Adding this to field description anyways.

File: assets/externalized/strategic-map-creature-lairs.json [hunk 8]
```diff
@@ -0,0 +1,181 @@
+/*
+ * Defines all the possible Crepitus creature lairs and spreading. There can be at most 1 lair activated in each (Sci-Fi) game.
+ *
+ * Field definitions:
+ *  - lairId:    A unique numeric ID for the lair. Must be an integer greater than zero.
+ *  - associatedMineId:    Creature lair must be located and associated with one mine.
+ *  - entranceSector:    Where the lair entrance is located. There must be an alternate map file (*_a.dat), which will be activated at lair initialization.
+ *  - sectors:    An ordered list of sectors making up the lair, specified as an array of [sector, sectorZ, habitatType]. This list should start with the innermost sector, which is the QUEEN_LAIR. The creatures will spread out outwards. Each sector must have a corresponding map file and defined in strategic-map-underground-sectors.json; "habitatType" must be one of: QUEEN_LAIR, LAIR, LAIR_ENTRANCE, INNER_MINE, OUTER_MINE, FEEDING_GROUNDS or MINE_EXIT. See Creature_Spreading.h for details.
+ *  - warpExit:    Destination for the "Travel to surface?" warp from deep underground
+ *  - attackSectors: List of town sectors and enemy insertion. Used by creatures to make town attacks
```
[the remark this answers is not in the document]
Comment (ja2-derek) [reply assets/externalized/strategic-map-creature-lairs.json]: Done

File: src/externalized/strategic/CreatureLairModel.cc (hunk 1 above)
Comment (lynxlynxlynx) [reply src/externalized/strategic/CreatureLairModel.cc:40]: Sounds fine. C++11 allows us to do it more cleanly

File: src/externalized/DefaultContentManager.cc [hunk 9]
```diff
@@ -1303,6 +1315,35 @@ const BloodCatSpawnsModel* DefaultContentManager::getBloodCatSpawnsOfSector(uint
 	return NULL;
 }
 
+const std::vector<const CreatureLairModel*> DefaultContentManager::getCreatureLairs() const
```
Comment (flaviojs) [inline src/externalized/DefaultContentManager.cc:1318]: You probably wanted to return a const reference here, you're returning a cost copy.

File: src/externalized/strategic/CreatureLairModel.cc [hunk 10]
```diff
@@ -0,0 +1,259 @@
...
+		obj.GetUInt("lairId"),
+		obj.GetUInt("associatedMineId"),
+		entranceSector, entranceSectorLevel,
+		readLairSectors(json["sectors"]),
+		readAttackSectors(json["attackSectors"]),
+		warpExitSector, warpExitGridNo
+	);
+}
+
+void CreatureLairModel::validateData(const std::vector<const CreatureLairModel*> lairs, const std::vector<const UndergroundSectorModel*> ugSectors, const uint8_t numMines)
```
Comment (flaviojs) [inline src/externalized/strategic/CreatureLairModel.cc:184]: You probably wanted to receive const references, but you're receiving const copies.

**Comment by flaviojs** [comment]
It seems that you like to use auto, which is fine, but you should know that auto in C++ is very limited and can be misleading when you are trying to figure out if something is a reference or a copy.

Personally I only use it for std iterator variables (can't think of anything else right now).

**Comment by ja2-derek** [comment]
> 
> 
> It seems that you like to use auto, which is fine, but you should know that auto in C++ is very limited and can be misleading when you are trying to figure out if something is a reference or a copy.
> 
> Personally I only use it for std iterator variables (can't think of anything else right now).

Thanks. I will keep that in mind.

Had used C# a bit, and get used to the auto type inference.

File: src/externalized/strategic/CreatureLairModel.cc (hunk 10 above)
Comment (ja2-derek) [reply src/externalized/strategic/CreatureLairModel.cc:184]: Sometimes I wonder if the compiler is smart enough or allowed to optimize this.
