### PR TITLE
Fix EPCs unescort functionality

### LINKED ISSUE #478: Skyrider placed randomly (?) in Drassen Airport
Sometimes, Skyrider-NPC is placed seemingly random on B13. Isn't he supposed to stay near his helicopter?
Having him hang around somewhere else is inconvenient and potentially dangerous for him. He would be much safer near his heli.
skyrider

Savedgame:
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/685626/SaveGame10.zip)

### PR DESCRIPTION
**Pull request by ShishkinP**
Closes #478

Fixed (or circumvented) issues:
1. Doesn't matter, if unescorted manually or by a proximity trigger (quest completion), NPCs are always put on the north entry point after a sector reload. From now on they'll be at the exact tile the player left them, if unescorted manually.
2. There's map editor placement info for Skyrider in the airport sector, but it's ignored.
3. There's no map editor placement info for Joey in his home sector.
4. Unescort-related placement/disappearance code is a bit scattered all over the place.

### CODE REVIEW

File: src/game/Tactical/Soldier_Profile.cc [hunk 1]
```diff
@@ -801,23 +802,12 @@ BOOLEAN UnRecruitEPC(ProfileID const pid)
...
-		p.sSector = s->sSector;
-	}
-
-	// how do we decide whether or not to set this?
-	p.fUseProfileInsertionInfo  = TRUE;
-	p.ubMiscFlags3             |= PROFILE_MISC_FLAG3_PERMANENT_INSERTION_CODE;
+	gMercProfiles[pid].ubMiscFlags3 |= PROFILE_MISC_FLAG3_PERMANENT_INSERTION_CODE;
+	gMercProfiles[pid].ubStrategicInsertionCode = INSERTION_CODE_GRIDNO;
+	gMercProfiles[pid].usStrategicInsertionData = s->sGridNo;
+	gMercProfiles[pid].fUseProfileInsertionInfo = TRUE;
```
Comment (lynxlynxlynx) [inline src/game/Tactical/Soldier_Profile.cc:810]: Why don't you use `p` like the rest of the code?

Comment (ShishkinP) [reply src/game/Tactical/Soldier_Profile.cc]: Strange but my IDE indicated some of its members are inaccessible. Yet now it's all fine with it. It's probably my slow notebook's problem.

**Comment by lynxlynxlynx** [comment]
LGTM, thanks!
