### PR TITLE
AnimCache should not evict in-use surface

### LINKED ISSUE #139: Crash after cutscene
Originally reported by: **Robs Soie (Bitbucket: [Robsoie](http://bitbucket.org/Robsoie), GitHub: [Robsoie](http://github.com/Robsoie))**

---

In Early game, using regular mercs (no IMP) , i went to meet Miguel at the hideout in Omerta and recruited Ira , that joined the team 2 as team 1 was full.

I assigned team1 to travel to the airport sector of Drassen, while i moved Ira to behind some sandbags close to the rebels hideout just in case.

The "Meanwhile" screen appeared , launching the cutscene with Deidranna 

Then back into the game i moved out of the pause to get my team moving to Drassen and JA2 just crashed there with the error popup :
ERROR : caught unhandled exception:
Palette creation failed, soldier has invalid animation
Creating an emergency savegame succeeded (error.sav)
Please report ....

using JA2 with only stracciatella from the version : ja2-v0.12.352-win  and no other mod
on winxp sp3 

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/139

### LINKED ISSUE #721: crash after scene about capturing northeast sam site
The game crashed after showing the animation about northeast SAM site being captured.

```
...
2018/06/28 22:02:48 WARNING [Animations      ] Animation Surface for Body 1, animation STANDING, surface 152 not loaded.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Palette creation failed, soldier has invalid animation
Creating an emergency savegame succeeded (error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame.
Neúspěšně ukončen (SIGABRT)
```

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git | JA2 Gold v1.10  |    (don't know)    |    yes     |

[crashaftersamscene.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2238268/crashaftersamscene.zip)

### PR DESCRIPTION
**Pull request by ja2-derek**
Fixes #721, which is caused by evicting an in-use animation surface from AnimCache.

Should also fix #139.

## Summary

- For cache eviction, consider also the current `pSoldier->usAnimSurface`
- We can have up to 2 "reserved" cache slots, the max cache size must be larger than 2
- `guiCacheSize` increased from 2 to 3
    - This may lead to higher memory usage, extra ~40 bytes for each soldier
    - AnimCache does not get saved, so it does not impact game saves
    - Cache size might be made configurable, some day. See also https://github.com/ja2-stracciatella/ja2-stracciatella/commit/235a49d07fb8bf5e5ce1959e7720a6bf6234eda1

## Testing

Bug described [here](https://github.com/ja2-stracciatella/ja2-stracciatella/issues/721#issuecomment-654258818) can no longer be reproduced. Now it hits the added eviction check as expected, with log `Anim Cache: REJECTING Slot 1 IN-USE ANIM SURFACE ( Soldier 0, Surface 202 )`.

## Related commits

This bug probably does not manifest in vanilla, because vanilla returns `FALSE` and pretends nothing happened. See below:

- https://github.com/ja2-stracciatella/ja2-stracciatella/commit/3aab5adc11058a1cb2ac7415234e83064f54624b
- https://github.com/ja2-stracciatella/ja2-stracciatella/commit/a8278d914b3f916d152483ef342e470a3fc0c32d

### CODE REVIEW

File: src/game/Tactical/Animation_Cache.cc [hunk 1]
```diff
@@ -110,21 +110,21 @@ void GetCachedAnimationSurface(UINT16 const usSoldierID, AnimationSurfaceCacheTy
...
-
-			// Decrement
-			pAnimCache->sCacheHits[ ubLowestIndex ] = 0;
-			pAnimCache->usCachedSurfaces[ ubLowestIndex ] = EMPTY_CACHE_ENTRY;
-			pAnimCache->ubCacheSize--;
-		}
-		else
-		{
-			SLOGW("Anim Cache: No slots can be evicted");
+			SLOGW(ST::format("Anim Cache: No perferred cache slot for eviction ( Soldier {} )", usSoldierID));
```
Comment (lynxlynxlynx) [inline src/game/Tactical/Animation_Cache.cc:115]:
```suggestion
			SLOGW(ST::format("Anim Cache: No preferred cache slot for eviction ( Soldier {} )", usSoldierID));
```

**Comment by lynxlynxlynx** [comment]
Thanks :)
