### PR TITLE
Normalize structure tiles

### LINKED ISSUE #1107: Game crashes on helicopter coming back to Drassen
### What is wrong
I attach a save (both error and one to trigger it). Just load SaveGame10.sav, move Skyrider anywhere (either empty or with someone) and back to Drassen (or allow him to come back himself). You get crash:

```
2020-06-07T20:42:24 [ INFO] game/GameLoop.cc: Version #:     Build 04.12.02
2020-06-07T20:42:41 [ WARN] game/Tactical/Tactical_Save.cc: SynchronizeItemTempFile() Reported 0, should be 16
2020-06-07T20:43:13 [ WARN] game/Strategic/Scheduling.cc: Schedule callback occurred outside of tactical -- Auto processing!
2020-06-07T20:43:13 [ WARN] game/Strategic/Scheduling.cc: Schedule callback occurred outside of tactical -- Auto processing!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to add node to world
Creating an emergency savegame succeeded (error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame.
fish: “./ja2” terminated by signal SIGABRT (Abort)
```

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
Both HEAD and 0.16.x, vanilla, don't know

### PR DESCRIPTION
**Pull request by ja2-derek**
Fixes #1107 and #722. And probably all helicopter crash issues.

### Summary 

This PR attempts to fix JSD data issues. For detailed explanation refer to the issue and the comments in code. 

The normalization is called after loading structure from file. It does nothing on most structures. It happens only when the structure has no tile of (0, 0) rel position. The function will then shift all tiles so that one of them is (0, 0).

### Testing

Briefly tested different sectors, so far I only find the normalization taking effect in I6 (Estoni), B13 (Drassen airport) and C13 (dead airstrip). All of them has helicopter structures.

The landed copter looks fine to me in both B13 and I6 after this fix.

### CODE REVIEW

File: src/game/TileEngine/Structure.cc [hunk 1]
```diff
@@ -297,6 +297,43 @@ static void LoadStructureData(char const* const filename, STRUCTURE_FILE_REF* co
...
+
+	if (minDistFromBase == 0)
+	{
+		// Data is fine. Nothing to do.
+		return;
+	}
+
+	SLOGD(ST::format("Adjusting tiles relative positions by {}", -minDistFromBase));
+	int xDist = minDistFromBase % WORLD_COLS;
+	int yDist = minDistFromBase / WORLD_COLS;
```
Comment (lynxlynxlynx) [inline src/game/TileEngine/Structure.cc:328]: Shouldn't it be (I know they're the same currently):
```suggestion
	int yDist = minDistFromBase / WORLD_ROWS;
```

**Comment by lynxlynxlynx** [comment]
Does it also fix the save from #1010?

File: src/game/TileEngine/Structure.cc (hunk 1 above)
Comment (ja2-derek) [reply src/game/TileEngine/Structure.cc:328]: I am not sure how these can converted - but I am following this: 

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/00111f7d7ad12438871434bc676d5b120e184d39/src/game/TileEngine/Structure.cc#L338

**Comment by ja2-derek** [comment]
> 
> 
> Does it also fix the save from #1010?

 I cannot download the save from #1010.

File: src/game/TileEngine/Structure.cc (hunk 1 above)
Comment (lynxlynxlynx) [reply src/game/TileEngine/Structure.cc:328]: Heh, that one looks wrong to me as well. Is it not trying to just compute the 1d index from 2d coordinates?

Comment (ja2-derek) [reply src/game/TileEngine/Structure.cc:329]: I am not familiar on this enough to make such change. I'd rather keep it consistent with existing stuff.

Comment (lynxlynxlynx) [reply src/game/TileEngine/Structure.cc:329]: Nah, you're right, it's fine.

**Comment by njskalski** [comment]
I confirm fix works on my machine.

Btw, Xubuntu 20.04, nvidia proprietary.

**Comment by lynxlynxlynx** [comment]
Yay, teamwork. :)
